name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm i
    - name: Build package
      run: npm run build
    - run: git remote set-url --push origin https://yukipastelcat:$GITHUB_TOKEN@github.com/your/repo
    - name: Deploy Storybook
      run: npm run deploy:storybook -- --ci

