name: CI
on:
  push

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm run test:ci
