name: Continuous integration

on:
  pull_request:
    branches: [main, develop]

jobs:
  code-check:
    name: Run Frontend code check against ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-frontend-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install packages
        run: npm ci
      - name: Remove .npmrc file
        run: rm ~/.npmrc
      - name: Prettier check
        run: npm run prettier:check
      - name: Eslint check
        run: npm run lint
      - name: Unit tests
        run: npm test
